apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sinforops
  name: sinforops
spec:
  containers:
  - image: alpine
    name: alpine
    args:
     - sleep
     - "20000"
  - image: nginx
    name: webserver
    args:
     - sleep
     - "1800"
    volumeMounts:
    - mountPath: /sinforops
      name: volume-first
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: volume-first
    emptyDir:
      sizeLimit: 256Mi
