apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sinfas
    service: webserver
  name: sinfas
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args: 
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
