apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sinforops
  name: sinforops
spec:
  containers:
  - image: nginx
    name: sinforops
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
